employee_file = open("Employeees.txt", "r")
print(employee_file.readline())
print(employee_file.readline())
print(employee_file.readline())
print(employee_file.readline())
print(employee_file.readline())
employee_file.close()